spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/user/**
        - id: cart-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/cart/**
        - id: order-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/order/**
        - id: product-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/**
    
server:
  port: 8765
