# Fetching config from server at : http://localhost:8090
spring:
  application:
    name: cart-service
  cloud:
    config:
      uri: http://localhost:8090
  config:
    import: optional:configserver:http://localhost:8090


# Connection url for our DB
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrival=true
    username: root
    password: root03
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
# Show error message
server:
  error:
    include-message: always